### ISSUE TITLE
Rewrite - Change the logging behavior to log to Cloudwatch

### ISSUE THREAD

**Issue by JudsonStevens** [OperationCode/operationcode-pybot#358]
Currently we are strictly logging to standard output - we should switch to logging to Cloudwatch for anything higher than a development environment. This would impact staging and production.

An example method and configuration I've used for this before is below. If we use this configuration, it will standardize the output of the logs to include line numbers, environment, a datetime stamp, the function name, and the module name.

```python
def get_conditional_logger(
        cloudwatch_stream_name="default",
        cloudwatch_log_group=f"/aws/ecs/pybot/{os.getenv('RUN_ENV', 'missingenv').lower()}"
):
    """
    Returns a logger instance depending on conditions in the environment. For example, returns a logger that writes to the console locally if the DEBUG environment variable is set to Local.
    Parameters
    ----------
    cloudwatch_stream_name: str
        Default is the string 'default'. This is the name of the CloudWatch stream. If local debugging is set, this variable is not used.
    cloudwatch_log_group: str
        Default is the /aws/ecs/pybot log group. Used to set the log group that the logs will write to. If local debugging is set, this variable is not used.
    Returns
    -------
    Logger
    """
    with open('modules/logging/logging_config.yml') as log_config:
        config_dict = yaml.safe_load(log_config.read())
        logging.config.dictConfig(config_dict)
        logging_target = os.getenv("LOGGING_TARGET", "missingtarget").lower()
        if logging_target == "cloudwatch":
            cloudwatch_only_logger = retrieve_cloudwatch_logger(logging, cloudwatch_stream_name, cloudwatch_log_group)
            return cloudwatch_only_logger
        elif logging_target == "console":
            console_only_logger = retrieve_console_logger(logging)
            return console_only_logger
        elif logging_target == "combined":
            combined_logger = retrieve_combined_logger(logging, cloudwatch_stream_name, cloudwatch_log_group)
            return combined_logger
        else:
            console_only_logger = retrieve_console_logger(logging)
            console_only_logger.warning(f"LOGGING_TARGET environment variable not set or not valid, "
                                        f"logging_target: {logging_target}")
            return console_only_logger

def return_module_name(module_name_attribute):
    return module_name_attribute.__file__.split('/')[-1]


def retrieve_cloudwatch_logger(logging_with_config, cloudwatch_stream_name, cloudwatch_log_group):
    boto3_session = Session()
    cloudwatch_logger = logging_with_config.getLogger("cloudwatch_logger")
    cloudwatch_logger.__setattr__('stream_name', cloudwatch_stream_name)
    cloudwatch_logger.__setattr__('log_group', cloudwatch_log_group)
    cloudwatch_logger.__setattr__('boto3_session', boto3_session)
    cloudwatch_logger = AddEnvironmentAdapter(cloudwatch_logger, {"run_env": os.getenv("RUN_ENV", "missingenv")})
    return cloudwatch_logger


def retrieve_console_logger(logging_with_config):
    console_logger = logging_with_config.getLogger("console_logger")
    console_logger = AddEnvironmentAdapter(console_logger, {"run_env": os.getenv("RUN_ENV", "missingenv")})
    return console_logger


def retrieve_combined_logger(logging_with_config, cloudwatch_stream_name, cloudwatch_log_group):
    boto3_session = Session()
    combined_logger = logging_with_config.getLogger("combined_logger")
    # May need to change this to not be position dependent and iterate through the handlers if we have more than two
    combined_logger.handlers[1].__setattr__('stream_name', cloudwatch_stream_name)
    combined_logger.handlers[1].__setattr__('log_group', cloudwatch_log_group)
    combined_logger.handlers[1].__setattr__('boto3_session', boto3_session)
    combined_logger = AddEnvironmentAdapter(combined_logger, {"run_env": os.getenv("RUN_ENV", "missingenv")})
    return combined_logger


class AddEnvironmentAdapter(logging.LoggerAdapter):
    def process(self, msg, kwargs):
        return f"[ENV: {self.extra['run_env'].lower()}] text:[{msg}]", kwargs

```

```yaml
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(asctime)s.%(msecs)03d] [%(levelname)s] logger:%(name)s module:%(module)s func_name:%(funcName)s line_num:%(lineno)s %(message)s"
    datefmt: "%z %Y-%m-%d %H:%M:%S"
  cloudwatch:
    format: "[%(levelname)s] logger:%(name)s module:%(module)s func_name:%(funcName)s line_num:%(lineno)s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  watchtower:
    class: watchtower.CloudWatchLogHandler
    formatter: cloudwatch
    level: DEBUG
    send_interval: 60
    create_log_group: False
    create_log_stream: True
root:
  level: DEBUG
  propagate: False
  handlers: []
loggers:
  console_logger:
    handlers: [console]
    propagate: False
    level: DEBUG
  cloudwatch_logger:
    handlers: [watchtower]
    propagate: False
    level: DEBUG
  combined_logger:
    handlers: [console, watchtower]
    propagate: False
    level: DEBUG
```
